CFLAGS   += -w $(HTM_RETRIES) $(RETRY_POLICY)
CPPFLAGS := $(CFLAGS)
LIBS     += $(CPPFLAGS)  -I ../lib/ -L$(STM)/../lib -lstm -I../../../rapl-power -L../../../rapl-power -ltcmalloc -lpthread -lrt -lrapl -I$(STM)
LDFLAGS  += $(LIBS)
