CFLAGS   += -w $(HTM_RETRIES) $(RETRY_POLICY)

CPPFLAGS := $(CFLAGS)
LIBS     += $(CFLAGS) -I../lib/ -I../../../rapl-power/ -I ../../../stms/norec/ -lrt -mrtm -lm -L../../../rapl-power/ -lrapl -L../../../stms/norec/ -lnorec -ltcmalloc -lpthread
LDFLAGS  += $(LIBS)