CFLAGS   += -w $(HTM_RETRIES) $(RETRY_POLICY)
CPPFLAGS := $(CFLAGS)
LIBS     += $(CPPFLAGS)  -I ../lib/ -L$(STM) -lnorec -I../../../rapl-power -L../../../rapl-power -ltcmalloc  -lpthread -lrt -lrapl -I$(STM)
LDFLAGS  += $(LIBS)